### ISSUE TITLE
Event_id not being stored when setting a new security_violation

### ISSUE THREAD

**Issue by unintendedbear** [MusesProject/MusesServer#13]
One of the causes of the problems I'm having to link simple events with the decisions is that inside Rt2aeGlobal.java:

```java
public void storeComplexEvent(Event event, String message, String mode, String condition) {
// Database insertion
SecurityViolation securityViolation = new SecurityViolation();
...
securityViolation.setEventId(new BigInteger("2"));
...
dbManager.setSecurityViolation(securityViolation);
}
```

The event_id it's always set to "2"...

I'm assigning Xavier because the class is named Rt2ae***. But if Xavier is not in charge, please re-assign to the corresponding developer.

**Comment by szamarripa** [comment]
It is part of the Event Processor, so I will take this one.
