### ISSUE TITLE
Include data in corporate_policies table

### ISSUE THREAD

**Issue by unintendedbear** [MusesProject/MusesServer#21]
By translating natural-language written policies into some readable type for the DB.

**Comment by szamarripa** [comment]
This is done, what is yet to be done is to translate the RTF files of the available policies into xml format.

https://repository.musesproject.eu/websvn/listing.php?repname=Muses&path=%2FWorkgroups%2FPolicies+work+group%2Fsecurity_policies%2FMUSES+policies+-revised+by+S2%2F&#ae10c7e375ec90536c9f24113da6c57b4
