### ISSUE TITLE
License is not included in every file

### ISSUE THREAD

**Issue by JJ** [MusesProject/MusesServer#3]
So far I have detected it in a file by @yasali but probably @xaviertiti should also check whether it's included in its files. It would be a good idea to include it in the rules that files must fulfill before being commited. I don't know if that can be done automatically, @mrburvall

**Comment by yasali** [comment]
Sweden Connectivity has updated all classes with license headers

**Comment by yasali** [comment]
Please review all classes belong to you and then assign to Sergio.

**Comment by xaviertiti** [comment]
All my classes have already license headers

**Comment by yasali** [comment]
Thank Xavi (RT-Guy), I have also updated the license header in all of our classes.

**Comment by unintendedbear** [comment]
Mine too, I think, given the fact that classes DataMiner.java and KnowledgeCompiler.java were created by @szamarripa, even though I'm "filling" them.

**Comment by yasali** [comment]
Come on my friend Sergio, only you are left :-)

**Comment by szamarripa** [comment]
License headers added for every file
