### ISSUE TITLE
To automatically populate DEVICES table

### ISSUE THREAD

**Issue by unintendedbear** [MusesProject/MusesServer#37]
As devices are supposed to register themselves in MUSES... Users will be registered via Muse SRM (server GUI), then when devices log in into the system, an entry in devices tables should be added with device information.

**Comment by szamarripa** [comment]
Currently, the devices are registered when incoming events are stored:

| device_id | name              | model     | description  | IMEI                 | OS_name | OS_version | trust_value | certificate | owner_type |

|       338 | luis              | domemodel | NULL         | 357737057014694      | NULL    | NULL       |         0.5 | NULL        | NULL       |

It still require to complete values that now are null, such as OS_name, Os_version and description.

**Comment by szamarripa** [comment]
This device registration is now complete
