### ISSUE TITLE
Add rules and policies to server DB

### ISSUE THREAD

**Issue by szamarripa** [MusesProject/MusesServer#43]

**Comment by unintendedbear** [comment]
Which will be the format of the rules? I mean, is there a way to translate from Drools to something like:

````
condition1 >= value1 AND condition2 == string2
THEN
STRONGDENY
````

without performing extreme parsing?

**Comment by szamarripa** [comment]
I would propose something like this:
rule "<name>"
    <attribute>*
when
    <conditional element>*
<conditional element>*
then
    <action>*
end

Hence, we could display a list of conditions and a list of actions, that are usually inferred as a DENY, or ALLOW.
Reference:
http://stackoverflow.com/questions/22253079/parse-drools-rule-file-with-java-regex
