### ISSUE TITLE
Update new field "date" in "muses_config" table and check it

### ISSUE THREAD

**Issue by unintendedbear** [MusesProject/MusesServer#44]
In order to be careful when reading the silent_mode in the configuration from muses_config table, the server should check the last configuration that was stored. The configuration can be changed from server GUI.

**Comment by unintendedbear** [comment]
Hi all!

Juan Luis just added this functionality in MusesSRM (commit https://github.com/MusesProject/MusesSRM/commit/45eaa39f6c9d487d4917bdb61b6fdd4e0353d0a5), so **please all**, ensure that in the code you are looking at the last row of the table (last configuration for silent mode).

**Comment by szamarripa** [comment]
Done, we use getMusesConfig method, which retrieves the last element of the findAll named query. Performing some testing we confirm that it returns the last row of the muses_config table.
