### ISSUE TITLE
MusesCorrelator.xml can not be opened

### ISSUE THREAD

**Issue by mrburvall** [MusesProject/MusesServer#7]
Description:
Error at startup of server on ubuntu:
16:16:47,632 ERROR eu.musesproject.server.eventprocessor.correlator.engine.AbstractDroolsEngine:236 - java.io.FileNotFoundException: ./MusesCorrelator.xml (Permission denied)

Version: 2015-01-19

Logs: 

16:16:47,247  INFO org.springframework.web.context.ContextLoader:221 - Root WebApplicationContext: initialization completed in 1665 ms
16:16:47,252  INFO eu.musesproject.server.eventprocessor.correlator.engine.CorrelationStartupServlet:27 - MUSES_TAGCorrelationStartupServlet
16:16:47,256  INFO eu.musesproject.server.eventprocessor.impl.EventProcessorImpl:164 - Starting temporal correlation...
16:16:47,258  INFO eu.musesproject.server.eventprocessor.impl.EventProcessorImpl:170 - Input stream is NOT null
16:16:47,267  INFO eu.musesproject.server.eventprocessor.impl.EventProcessorImpl:174 - URL rule path:/tmp/tomcat7-tomcat7-tmp/5-server/WEB-INF/classes/drl/
16:16:47,267  INFO eu.musesproject.server.eventprocessor.impl.EventProcessorImpl:177 - DRL absolute rule path:file:///tmp/tomcat7-tomcat7-tmp/5-server/WEB-INF/classes/drl/
16:16:47,632 ERROR eu.musesproject.server.eventprocessor.correlator.engine.AbstractDroolsEngine:236 - java.io.FileNotFoundException: ./MusesCorrelator.xml (Permission denied)

Reproduce: 
Deploy a muses server without MusesCorrelator.xml in /var/lib/tomcat7

Work Around: 
Copy file from ./var/lib/tomcat7/webapps/server/WEB-INF/classes/MusesCorrelator.xml
to /var/lib/tomcat7, give permissions to tomcat7 user

Solution: 
Change path.

**Comment by szamarripa** [comment]
Fixed by changing the path.
